### ISSUE TITLE
ClusterStorageContainer with `kit://` prefix and Kserve not working

### ISSUE THREAD

**Issue by dpnoworyta** [kitops-ml/kitops#817]
**Use case:**
Our idea is to use KitOps to push model files into OCI compatible repository in AWS ECR and use that model for serving in Kserve EKS. Kserve itself does support ECR (as `oci://` prefix in combination with supported model serving runtimes) but only when used as container repo.

**What I have checked**
I found that there is part of KitOps repo when something similar is already covered here: https://github.com/kitops-ml/kitops/tree/main/build/dockerfiles/KServe. 

First of I think that there is a typo in image path: https://github.com/kitops-ml/kitops/blob/98d3e1e1c29ae86a14446f89eec77d27d0fc5c22/build/dockerfiles/KServe/Dockerfile#L1 because it is pointing to image that it is not reachable:

```
ERROR: failed to solve: ghcr.io/kitops-ml/kit:next: failed to resolve source metadata for 
ghcr.io/kitops-ml/kit:next: failed to authorize: failed to fetch anonymous token: 
unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akitops-ml%2Fkit%3Apull&service=ghcr.io: 
403 Forbidden

docker pull ghcr.io/kitops-ml/kit:next
Error response from daemon: Head "https://ghcr.io/v2/kitops-ml/kit/manifests/next": denied
```

Should that point to `ghcr.io/kitops-ml/kitops:next` like your init container?
https://github.com/kitops-ml/kitops/blob/98d3e1e1c29ae86a14446f89eec77d27d0fc5c22/build/dockerfiles/init/Dockerfile#L3

Assuming the answer is yes, I've tried following further your guide in readme by creating `ClusterStorageContainer` and `InferenceService` that uses `kit://` prefix:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-movies-kitops-custom-storage
  namespace: kserve
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "kit://<ACCOUNT_ID>.dkr.ecr.eu-central-1.amazonaws.com/kserve/models:kitpacked-model-1"
```

**Issue**
Upon deploying inference manifest, there are few resources created, one of which is ReplicaSet that below log is from:
```
'Pod "sklearn-movies-kitops-custom-storage-predictor-856bfd8966-hklgn"
      is invalid: [spec.volumes[3].name: Duplicate value: "kserve-provision-location",
      spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/mnt/models":
      must be unique, spec.initContainers[1].name: Duplicate value: "kitops-storage-init"]'
    reason: FailedCreate
```
There is no container spawned, thus there is no log from it nor manifest used to create pod.
I'm guessing that I miss something out here or there is some underlying issue with example that you've provided. When did you test this integration? What was the version of KitOps and Kserve? Could you please take a look from your end?

**To Reproduce**
1. Follow KitOps Kserve example
2. Push model to ECR using `kit pack` and `kit push` commands
3. Deploy example inference manifest
4. Check `ReplicaSet` for error

**Version**
- KitOps: `next`, `v1.3.0`
- Kserve: `v0.14.1`
- K8s: `v1.31.3`

**Comment by gorkem** [comment]
We have recently moved to a new GitHub organization and it sounds like this is one of the MIA packages. I will try to get this sorted today.

**Comment by gorkem** [comment]
I am issuing the PRs; however, if you prefer to try this yourself, please switch to using `ghcr.io/kitops-ml/kitops:next` as the base for your `$KIT_KSERVE_IMAGE`. Then, use the manifest below to create the `ClusterStorageContainer`. Note that the main difference from the previous instructions is the `metadata.name`, as KServe requires a specific name.


```
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: kitops
spec:
  container:
    name: storage-initializer
    image: $KIT_KSERVE_IMAGE
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
  supportedUriFormats:
  - prefix: kit://
  ```
