### ISSUE TITLE
Kit Dev command failing with Kitfile referencing subdirectory?

### ISSUE THREAD

**Issue by bmicklea** [kitops-ml/kitops#880]
**Describe the bug**
When running the `kit dev start` command with a kitfile that references a model in a subfolder:

```yaml
model:
  name: pure-dove-llama32_1b_q4.gguf
  path: model
```

...the `kit dev start` command fails to load the model.

However, when you explicitly name the model under the folder in the Kitfile:

```yaml
model:
  name: pure-dove-llama32_1b_q4.gguf
  path: model/pure-dove-llama32_1b_q4.gguf
```

then kit dev start works fine. My understanding is that referencing the folder where the model is located should be sufficient to allow kit dev start to execute.

**Version**
Kit 1.5.1

**Comment by amisevsk** [comment]
We should document that using a full path to the file is ideal, as it allows for easier processing of files (e.g. allowing you to unpack only the weights, or unpack everything except the weights), but this is still a bug.

E.g. I believe a better Kitfile (that captures the same set of files) would be
```yaml
model:
  name: pure-dove-llama32_1b_q4.gguf
  path: model/pure-dove-llama32_1b_q4.gguf
  parts:
    - path: model/
```
